DROP TABLE MEMBER2;
CREATE TABLE MEMBER2(
    ID VARCHAR2(20) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    BIRTH DATE,
    GENDER VARCHAR2(1),
    EMAIL VARCHAR2(50),
    TEL VARCHAR2(30),
    ADDRESS VARCHAR2(100)
);
INSERT INTO MEMBER2 (ID,PW, NAME, BIRTH, GENDER) VALUES 
    ('AAA', 'AAA', '이에이', '1996-09-09','F');
    INSERT INTO MEMBER2 (ID,PW, NAME, BIRTH, GENDER) VALUES 
    ('BBB', 'BBB', '이비이', '1996-09-09','F');
    INSERT INTO MEMBER2 (ID,PW, NAME, BIRTH, GENDER) VALUES 
    ('CCC', 'CCC', '이씨이', '1996-09-09','M');
SELECT * FROM MEMBER2;    
COMMIT;
--ID 중복체크
SELECT * FROM MEMBER2 WHERE ID='AAA';