--[III] JOIN : 테이블 2개 이상을 연결하여 검색
--RDB
SELECT * FROM EMP WHERE ENAME = 'SCOTT'; -- DEPTNO : 20;
SELECT * FROM DEPT;
-- CROSS JOIN (FROM절에 테이블 2개 이상)
SELECT * FROM EMP, DEPT WHERE ENAME ='SCOTT'; -- 4행 = EMP의 1행 * DEPT의 4행
SELECT * FROM EMP, DEPT; -- 56행 >> EMP의 14행, DEPT의 4행
-- EQUI JOIN (공통 필드인 DEPTNO값이 일치되는 조건만 JOIN)
SELECT EMPNO, ENAME, D.DEPTNO, DNAME, LOC 
    FROM EMP E, DEPT D -- AS나 ""쓰면 안된다. 
    WHERE E.DEPTNO=D.DEPTNO;

SELECT EMPNO NO, ENAME, E.DEPTNO, DNAME, LOC FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO -- EMP.DEPTNO 이런거 안된다. 테이블에 별칭을 입력하면 별칭만 써야 한다.
    ORDER BY EMPNO;

-- 급여가 2000이상인 직원만 이름, 업무(JOB), 급여, 부서명, 근무지 출력
SELECT ENAME, JOB, SAL, DNAME, LOC 
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND SAL>=2000;
-- LOC이 CHICAGO인 사람의 이름, 업무, 급여를 출력
SELECT ENAME, JOB, SAL
    FROM EMP E, DEPT D
    WHERE LOC='CHICAGO' AND E.DEPTNO=D.DEPTNO;
