--[V] 그룹함수 : SUM, AVG, MIN, MAX, COUNT, STDDEV, VARIANCE
SELECT ENAME, ROUND(SAL, -3)
    FROM EMP;
SELECT MAX(SAL) 
    FROM EMP;
--SELECT ENAME, MAX(SAL) FROM EMP; --> VI장 서브쿼리에서 해결    
SELECT DEPTNO, MAX(SAL) 
    FROM EMP 
    GROUP BY DEPTNO;
-- 1. 그룹함수들 실습
SELECT ROUND(AVG(SAL),2) 
    FROM EMP;
SELECT COUNT(*) 
    FROM EMP; -- EMP테이블의 행(ROW)수
SELECT AVG(SAL), SUM(SAL)/COUNT(SAL) 
    FROM EMP;
SELECT AVG(COMM), SUM(COMM), COUNT(COMM), SUM(COMM)/COUNT(COMM)
    FROM EMP;
-- SAL의 평균, 합, 최소값, 최대값, 분산, 표준편차
SELECT AVG(SAL), SUM(SAL), MIN(SAL), MAX(SAL), ROUND(VARIANCE(SAL)), ROUND(STDDEV(SAL)), ROUND(SQRT(VARIANCE(SAL)))
    FROM EMP;
-- 그룹함수 MAX, MIN, COUNT는 숫자형, 문자형, 날짜형 모두 사용가능.
--  가장 최근에 입사한 사원의 입사일과 입사한지 가장 오래된 사원의 입사일
SELECT HIREDATE
    FROM EMP
    WHERE HIREDATE='83/01/12' OR HIREDATE='80/12/17';
 -- WHERE HIREDATE=MAX(HIREDATE) OR HIREDATE = MIN(HIREDATE);안됌
SELECT MAX(HIREDATE)||' 최근 입사 : '||TO_CHAR(MIN(TRUNC((SYSDATE-HIREDATE))),'99,999')|| '일 근무, '|| MIN(HIREDATE)||' 최초입사 :' ||TO_CHAR(MAX(TRUNC((SYSDATE-HIREDATE))),'99,999')||'일 근무'
    FROM EMP;
--10번 부서 소속의 사원 급여 평균
SELECT AVG(SAL)
    FROM EMP
    WHERE DEPTNO=10;
    
-- 2. GROUP BY 절
--부서번호별 최대급여
SELECT DEPTNO, MAX(SAL)
    FROM EMP 
    GROUP BY DEPTNO;
--부서번호별 사원수, 최대급여, 최소급여, 평균급여(소수점 2자리)
SELECT DEPTNO, COUNT(*), MAX(SAL), MIN(SAL), ROUND(AVG(SAL),2)
    FROM EMP
    GROUP BY DEPTNO;
--SAL이 5000미만인 사원에 대해서만 부서번호별 사원수, 최대급여, 최소급여, 평균급여
SELECT DEPTNO, COUNT(*), MAX(SAL), MIN(SAL), AVG(SAL)
    FROM EMP
    WHERE SAL<5000
    GROUP BY DEPTNO;
-- 부서명별 사원수, 최대급여, 최소급여, 평균급여
SELECT DNAME, COUNT(*), MAX(SAL), MIN(SAL), AVG(SAL)
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO
    GROUP BY DNAME;
--3. HAVING 절
--부서번호별 평균 급여(평균급여가 2000이상인 부서만 출력)
SELECT DEPTNO, AVG(SAL) 
    FROM EMP
    GROUP BY DEPTNO
    HAVING AVG(SAL)>=2000; --필드의 별칭은 ORDER BY 절에서만 사용 가능(HAVING에서는 못씀.)
SELECT DEPTNO,SUM(SAL)
    FROM EMP
    GROUP BY DEPTNO;
SELECT DEPTNO,SUM(SAL)
    FROM EMP
    GROUP BY ROLLUP(DEPTNO); --ROLLUP 그룹별로 요약하여 출력
SELECT DEPTNO, JOB, SUM(SAL) 
    FROM EMP
    GROUP BY DEPTNO, JOB
    ORDER BY DEPTNO;
SELECT DEPTNO, JOB, SUM(SAL) 
    FROM EMP
    GROUP BY ROLLUP(DEPTNO, JOB);