CREATE TABLE BOOKCATEGORY(
    CATEGORYCODE NUMBER(3),
    CATEGORYNAME VARCHAR2(20) UNIQUE,
    OFFICE_LOC VARCHAR2(20) NOT NULL,
    PRIMARY KEY(CATEGORYCODE));
DROP TABLE BOOKCATEGORY;
DROP TABLE BOOK1;   
CREATE TABLE BOOK1(
    CATEGORYCODE NUMBER(3),
    bookNO VARCHAR2(12) PRIMARY KEY,
    bookNAME VARCHAR2(30),
    PUBLISHER VARCHAR(20),
    PUBYEAR NUMBER(4) DEFAULT TO_NUMBER(EXTRACT(YEAR FROM SYSDATE),'9999'),
    FOREIGN KEY(CATEGORYCODE) REFERENCES BOOKCATEGORY(CATEGORYCODE));
    
INSERT INTO BOOKCATEGORY VALUES (100,'철학','3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (200,'인문','3층 인문실');
INSERT INTO BOOKCATEGORY VALUES (300,'자연과학','4층 과학실');
INSERT INTO BOOKCATEGORY VALUES (400,'IT','4층 과학실');
INSERT INTO BOOK1 VALUES (100,'100A01','철학자의 삶','더존출판',2021);
INSERT INTO BOOK1 (bookno, bookNAME, PUBLISHER) VALUES ('400A01','이것이 DB다','더존출판');
-- 평소에 콤보박스로 입력해서 NOT NULL이 필요없긴 하다. 해주면 좋고. 
SELECT * FROM BOOK1;
SELECT * FROM BOOKCATEGORY;
DESC BOOK1;
DESC BOOKCATEGORY;
    
    