DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUS_SQ;
CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(4),
    LEVELNAME VARCHAR2(20) NOT NULL,
    PRIMARY KEY(LEVELNO));
CREATE TABLE CUSTOMER(
    CNO NUMBER(4),
    CNAME VARCHAR2(20) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(20) UNIQUE,
    POINT NUMBER(10), 
    LEVELNO NUMBER(4),
    PRIMARY KEY(CNO),
    FOREIGN KEY(LEVELNO) REFERENCES CUS_LEVEL(LEVELNO));
CREATE SEQUENCE CUS_SQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
INSERT INTO CUS_LEVEL VALUES (1,'VVIP');
INSERT INTO CUS_LEVEL VALUES (2,'VIP');
INSERT INTO CUS_LEVEL VALUES (3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4,'BLACK');
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, 'È«±æµ¿', '21/06/10','010-9999-9999',0,1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, 'ÀÌÃ¶¼ö', '20/11/12','010-8888-8888',NULL,2);

SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD') JOINDATE, PHONE, POINT+300 POINT, LEVELNAME 
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO;
commit    

