-- [VIII] SEQUENCE 순차번호 생성기, 대부분 인위적인 PK 사용 용도
-- CREATE SEQUENCE sequence_name
-- [INCREMENT BY n] [START WITH n]
-- [MAXVALUE n][MINVALUE n]
-- [CYCLE|NOCYCLE]
-- [CACHE n| NOCACHE];
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 --생략해도 됨 기본값이 START WITH1
    INCREMENT BY 1 --생략해도 됨 기본값이 INCREMENT BY 1
    MAXVALUE 9999  -- 기본값은 무한.
    MINVALUE 1 -- 기본값은 무한.
    NOCACHE
    NOCYCLE;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR(100),
    LAST_MODIFYED DATE DEFAULT SYSDATE);
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL,'홍길동',NULL,'서울시 마포구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL,'홍길동','010-9999-9999','서울시 서대문구');--재입력시 에러 발생하고 SEQ.NEXTVAL는 이미 실행했기 때문에 하나 늘어남.
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;
ROLLBACK;
COMMIT;
-- DROP SEQUENCE sequence_name;    (삭제)
-- ALTER SEQUENCE sequence_name [INCREMENT BY n] [START WITH n][MAXVALUE n][MINVALUE n]

--EX.
CREATE SEQUENCE TEST_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_SEQ.CURRVAL FROM DUAL;