CREATE TABLE IdPw(
    ID VARCHAR2(40) PRIMARY KEY,
    PW VARCHAR2(120),
    TEL VARCHAR2(20),
    ADDRESS VARCHAR2(200),
    GENDER VARCHAR2(10),
    EMAIL VARCHAR2(200)
);
DROP TABLE IdPw;
SELECT * FROM IdPw;

commit